import * as fs from 'fs'
import * as path from 'path'

interface FeatureFlags {
  telemedicine: boolean
  labIntegration: boolean
  smsNotifications: boolean
  whatsappAutomation: boolean
  aiChatbot: boolean
  advancedAnalytics: boolean
}

const DEFAULT_FLAGS: FeatureFlags = {
  telemedicine: false,
  labIntegration: false,
  smsNotifications: false,
  whatsappAutomation: false,
  aiChatbot: false,
  advancedAnalytics: false,
}

function loadFeatures(): FeatureFlags {
  // Try loading from features.json first (generated by inject.ts)
  const jsonPath = path.resolve(__dirname, 'features.json')
  if (fs.existsSync(jsonPath)) {
    try {
      const raw = fs.readFileSync(jsonPath, 'utf-8')
      return { ...DEFAULT_FLAGS, ...JSON.parse(raw) }
    } catch {
      // fall through to env vars
    }
  }

  // Fallback to environment variables
  return {
    telemedicine: process.env.FEATURE_TELEMEDICINE === 'true',
    labIntegration: process.env.FEATURE_LAB_INTEGRATION === 'true',
    smsNotifications: process.env.FEATURE_SMS_NOTIFICATIONS === 'true',
    whatsappAutomation: process.env.FEATURE_WHATSAPP_AUTOMATION === 'true',
    aiChatbot: process.env.FEATURE_AI_CHATBOT === 'true',
    advancedAnalytics: process.env.FEATURE_ADVANCED_ANALYTICS === 'true',
  }
}

export const features = loadFeatures()

export function isFeatureEnabled(feature: keyof FeatureFlags): boolean {
  return features[feature] === true
}
